---
driver_plugin: vagrant
driver_config:
  provision_command: curl -L https://www.getchef.com/chef/install.sh | bash
 # require_chef_omnibus: true
  socket: 'tcp://192.168.42.43:4243'

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[celery::default]
    attributes: {}
